project:
  type: website
  preview:
    port: 5000

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fun_standards.qmd
        text: Fundamental Standards

      - text: Methods
        menu:
          - text: "Interviews"
            href: interviews.qmd
          - text: "Food"
            href: food.qmd
          - text: "Incentives"
            href: incentives.qmd

      - text: Analysis
        menu:
          - text: "Analysis Plan"
            href: analysis_plan.qmd
          - text: "Data Cleaning"
            href: data_prep.qmd
          - text: "Omni's Approach"
            href: approach.qmd
            
      - text: Resources
        menu:
          - text: "Codebook"
            href: codebook.qmd
    background: "#081c39"
    foreground: white
    logo: https://github.com/rfortherestofus/omni/blob/main/inst/assets/images/logo-no-text.png?raw=true
    logo-alt: Logo of the Omni Institute
    logo-href: https://www.omni.org/
  page-footer:
    center: "Copyright 2025, Omni Institute"
    right: |
      [![](https://github.com/rfortherestofus/omni/blob/main/inst/assets/images/logo.png?raw=true){fig-alt="Omni institute" width=100px}](https://www.omni.org/)

format:
  html:
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false
